backend:
  name: github
  repo: lkadalski/blog
  branch: master
  base_url: https://sveltia-cms-auth.kadalski-lukasz.workers.dev
media_folder: static/media
public_folder: media
collections:
  - name: 'codex'
    label: 'Codex'
    folder: 'content/codex'
    create: true
    #slug: '{{slug}}'
    path: '{{slug}}/index'
    editor:
      preview: false
    media_folder: ''
    public_folder: ''
    #--------------------------
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ssZ' }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'screen dump'
    label: 'Screen Dump'
    folder: 'content/screen_dump'
    create: true
    #slug: '{{slug}}'
    path: '{{slug}}/index'
    editor:
      preview: false
    media_folder: ''
    public_folder: ''
    #--------------------------
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ssZ' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    #slug: '{{slug}}'
    path: '{{slug}}/index'
    editor:
      preview: false
    media_folder: ''
    public_folder: ''
    #--------------------------
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DDTHH:mm:ssZ' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: 'Body', name: 'body', widget: 'markdown' }
